version: '3.7'
services:
  app:
    build:
      context: .
    container_name: wp-app-${CONTAINER_PREFIX}
    restart: always
    volumes:
      - "./frontend/public:/app/frontend/public"
      - "./frontend/src:/app/frontend/src"
    command: npm run dev
    
    ports:
      - ${APP_PORT}:9000
